spring:
  application:
    name: legal-case-tracker

  datasource:
    url: jdbc:mysql://localhost:3306/legalcase?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org.springframework: INFO
    com.ahmet.hasan.yakup.esra.legalcase: DEBUG