version: '3.8'

services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: legalcase-mysql
    ports:
      - "3307:3306"  # Host port 3307'yi container port 3306'ya yönlendirin
    environment:
      MYSQL_DATABASE: legalcasedb
      MYSQL_USER: legalcaseuser
      MYSQL_PASSWORD: legalcasepass
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/main/resources/db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./src/main/resources/db/init-data.sql:/docker-entrypoint-initdb.d/2-init-data.sql
      - ./docker/mysql/init-keycloak-db.sql:/docker-entrypoint-initdb.d/3-init-keycloak-db.sql
    networks:
      - legalcase-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "legalcaseuser", "-plegalcasepass"]
      interval: 10s
      timeout: 5s
      retries: 5

  # phpMyAdmin for Database Management (Optional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: legalcase-phpmyadmin
    ports:
      - "5050:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - legalcase-network
    depends_on:
      - mysql
    restart: unless-stopped

  # Keycloak Identity Provider
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    container_name: legalcase-keycloak
    command: 
      - "start-dev"
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: legalcaseuser
      DB_PASSWORD: legalcasepass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/legalcase-realm.json
    volumes:
      - ./docker/keycloak/import/legalcase-realm.json:/tmp/legalcase-realm.json
    ports:
      - "8090:8080"
    networks:
      - legalcase-network
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  # Legal Case Tracker Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: legalcase-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/legalcasedb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: legalcaseuser
      SPRING_DATASOURCE_PASSWORD: legalcasepass
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080
      KEYCLOAK_REALM: legalcase
      KEYCLOAK_RESOURCE: legalcase-app
      KEYCLOAK_CREDENTIALS_SECRET: legalcase-secret
      KEYCLOAK_PUBLIC_CLIENT: "false"
      AUTH_PROVIDER: keycloak
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - legalcase-network
    depends_on:
      - mysql
      - keycloak
    restart: unless-stopped

# Networks
networks:
  legalcase-network:
    driver: bridge

# Volumes
volumes:
  mysql-data: